from turtle import Turtle,Screen,bgcolor
turtle = Turtle()
screen = Screen()

turtle.goto(-200,-200)
turtle.fillcolor("green")
turtle.begin_fill()
turtle.goto(-200,200)
turtle.goto(200,200)
turtle.goto(200,-200)
turtle.end_fill()

turtle.goto(0,-200)
turtle.goto(0,100)
turtle.write("1", font=("Arial", 10, "normal"))
turtle.goto(0,200)
turtle.write("b", font=("Arial", 20, "normal"))
turtle.goto(0,0)
turtle.goto(-200,0)
turtle.goto(100,0)
turtle.write("1", font=("Arial", 10, "normal"))
turtle.goto(200,0)
turtle.write("a", font=("Arial", 20, "normal"))
turtle.penup()
turtle.goto(100,0)
turtle.pendown()
turtle.setheading(90)
turtle.fillcolor("red")
turtle.begin_fill()
turtle.circle(100,90)
turtle.goto(0,0)
turtle.end_fill()

screen.exitonclick()